## Code Cell - Celda de Codigo

Contiene código Python que se puede ejecutar para realizar operaciones, crear variables y llamar funciones.

In [1]:
nombre = "Ana"
print(f"Hola, {nombre}")

Hola, Ana

## Markdown cell — Celda de texto

Permite documentar el notebook con títulos, subtítulos, listas, enlaces, explicaciones y texto con formato.

# Mi primer notebook
Este notebook contiene ejemplos de Python.
- Variables
- Operaciones

## Output — Resultado de ejecución

Es el resultado que aparece debajo de una celda después de ejecutarla. Puede ser texto, números, tablas, gráficos o mensajes de error.

In [2]:
10 + 5

15

## Variables y tipos de datos básicos

Una **variable** es un nombre que utilizamos para almacenar y acceder a un valor en Python.

Cada valor tiene un **tipo de dato**, que determina qué clase de información representa.

| Tipo | Descripción | Ejemplo |
|---|---|---|
| `int` | Número entero | `28` |
| `float` | Número decimal | `8.7` |
| `str` | Cadena de texto | `"Ana"` |
| `bool` | Valor lógico | `True` o `False` |

La función `type()` permite conocer el tipo de dato de un valor o una variable.

In [3]:
edad = 28              # int
promedio = 8.7         # float
nombre = "Ana"         # str
aprobado = True        # bool

print(type(edad), type(promedio))
print(type(nombre), type(aprobado))

<class 'int'> <class 'float'>
<class 'str'> <class 'bool'>

## Operadores y expresiones

Los **operadores** permiten realizar cálculos, comparar valores y combinar condiciones. Una **expresión** es una combinación de valores, variables y operadores que produce un resultado.

### 1. Operadores aritméticos

| Operador | Descripción | Ejemplo |
|---|---|---|
| `+` | Suma | `5 + 2` → `7` |
| `-` | Resta | `5 - 2` → `3` |
| `*` | Multiplicación | `5 * 2` → `10` |
| `/` | División | `5 / 2` → `2.5` |
| `//` | División entera | `5 // 2` → `2` |
| `%` | Módulo (residuo) | `5 % 2` → `1` |
| `**` | Potencia | `5 ** 2` → `25` |

### 2. Operadores de comparación

Comparan dos valores y devuelven un resultado booleano: `True` o `False`.

- `==` igual que
- `!=` diferente de
- `<` menor que
- `<=` menor o igual que
- `>` mayor que
- `>=` mayor o igual que

**Importante:** `=` asigna un valor; `==` compara dos valores.

### 3. Operadores lógicos

Permiten combinar o invertir condiciones.

- `and`: devuelve `True` cuando ambas condiciones son verdaderas.
- `or`: devuelve `True` cuando al menos una condición es verdadera.
- `not`: invierte el resultado lógico.

### 4. Orden de las operaciones

Python sigue reglas de precedencia para evaluar expresiones. Los paréntesis `()` permiten indicar explícitamente qué operaciones deben realizarse primero y hacen el código más fácil de leer.

In [4]:
subtotal = 3 * 25.50

es_mayor = subtotal > 50
con_descuento = es_mayor and subtotal >= 75

print(subtotal, es_mayor, con_descuento)

76.5 True True

In [5]:
precio = 120
cantidad = 2

total = precio * cantidad
es_caro = total >= 200
tiene_descuento = es_caro and cantidad > 1

print("Total:", total)
print("¿Es caro?", es_caro)
print("¿Tiene descuento?", tiene_descuento)

Total: 240
¿Es caro? True
¿Tiene descuento? True

## Colecciones: listas (`list`)

Una **lista** es una colección que permite almacenar varios elementos en una sola variable. Las listas mantienen el orden de sus elementos y pueden modificarse después de crearse.

### Características principales

- **Orden:** los elementos conservan su posición.
- **Índices:** comienzan en `0`, por lo que el primer elemento está en la posición `0`.
- **`append(elemento)`:** agrega un elemento al final de la lista.
- **`len(lista)`:** devuelve la cantidad de elementos.
- **Mutabilidad:** podemos modificar, agregar o eliminar elementos.

### Operaciones básicas

| Operación | Descripción |
|---|---|
| `lista[0]` | Accede al primer elemento |
| `lista[-1]` | Accede al último elemento |
| `lista.append(x)` | Agrega `x` al final |
| `len(lista)` | Devuelve el número de elementos |
| `lista[1:3]` | Obtiene elementos desde el índice 1 hasta antes del 3 |
| `lista.sort()` | Ordena la lista en el mismo objeto |

In [6]:
calificaciones = [8.5, 6.0, 9.2, 4.8, 7.5]

# Calcular el promedio
promedio = sum(calificaciones) / len(calificaciones)

# Identificar las calificaciones aprobatorias
aprobadas = []

for calificacion in calificaciones:
    if calificacion >= 6:
        aprobadas.append(calificacion)

# Agregar una nueva calificación
calificaciones.append(9.0)

print("Calificaciones:", calificaciones)
print("Cantidad:", len(calificaciones))
print("Promedio original:", round(promedio, 2))
print("Calificaciones aprobatorias:", aprobadas)

Calificaciones: [8.5, 6.0, 9.2, 4.8, 7.5, 9.0]
Cantidad: 6
Promedio original: 7.2
Calificaciones aprobatorias: [8.5, 6.0, 9.2, 7.5]

## Estructuras de control en Python

Las **estructuras de control** permiten modificar el flujo de ejecución de un programa. Con ellas podemos tomar decisiones, repetir instrucciones y procesar colecciones de datos.

### 1. Condicionales: `if`, `elif` y `else`

Permiten ejecutar diferentes bloques de código según se cumplan determinadas condiciones.

**Sintaxis:**

```python
if condicion_1:
    # Se ejecuta si condicion_1 es verdadera
elif condicion_2:
    # Se ejecuta si condicion_1 es falsa
    # y condicion_2 es verdadera
else:
    # Se ejecuta si ninguna condición anterior se cumple
```

- `if`: evalúa la primera condición.
- `elif`: evalúa otra condición si las anteriores fueron falsas.
- `else`: ejecuta una alternativa cuando ninguna condición anterior se cumple.
- Los dos puntos `:` indican el inicio del bloque.
- La indentación define qué instrucciones pertenecen a cada bloque.

### 2. Bucle `for`

Se utiliza para recorrer elementos de una colección o repetir instrucciones un número determinado de veces.

**Sintaxis:**

```python
for elemento in coleccion:
    # Instrucciones que se repiten
```

Ejemplo de estructura con `range()`:

```python
for numero in range(5):
    print(numero)
```

`range(5)` genera los valores del 0 al 4.

### 3. Bucle `while`

Repite un bloque de código mientras una condición sea verdadera. Es útil cuando no conocemos de antemano cuántas iteraciones serán necesarias.

**Sintaxis:**

```python
while condicion:
    # Instrucciones que se repiten
    # Actualizar el estado para evitar un bucle infinito
```

**Importante:** si la condición nunca se vuelve falsa, el bucle puede ejecutarse indefinidamente.

### Resumen

| Estructura | Propósito |
|---|---|
| `if / elif / else` | Tomar decisiones |
| `for` | Recorrer una colección o secuencia |
| `while` | Repetir mientras se cumpla una condición |

In [8]:
# Sistema de análisis de calificaciones
estudiantes = [
    {"nombre": "Ana", "calificacion": 95},
    {"nombre": "Luis", "calificacion": 72},
    {"nombre": "Marta", "calificacion": 58},
    {"nombre": "Carlos", "calificacion": 84},
    {"nombre": "Sofia", "calificacion": 40}
]

resultados = []
indice = 0
limite = len(estudiantes)

# WHILE: procesa registros mientras queden estudiantes
while indice < limite:

    estudiante = estudiantes[indice]
    nombre = estudiante["nombre"]
    calificacion = estudiante["calificacion"]

    # IF / ELIF / ELSE: clasifica el rendimiento
    if calificacion >= 90:
        nivel = "Excelente"
    elif calificacion >= 80:
        nivel = "Muy bueno"
    elif calificacion >= 60:
        nivel = "Aprobado"
    else:
        nivel = "Reprobado"

    # Guarda el resultado de cada estudiante
    resultados.append({
        "nombre": nombre,
        "calificacion": calificacion,
        "nivel": nivel
    })

    indice += 1  # Avanza al siguiente estudiante

# FOR: muestra el reporte final
print("REPORTE DE CALIFICACIONES")
print("-" * 40)

for resultado in resultados:
    print(
        f"{resultado['nombre']:<10} | "
        f"{resultado['calificacion']:>3} | "
        f"{resultado['nivel']}"
    )

# FOR + IF: calcula estadísticas
aprobados = 0
excelentes = 0
suma_calificaciones = 0

for resultado in resultados:
    suma_calificaciones += resultado["calificacion"]

    if resultado["calificacion"] >= 60:
        aprobados += 1

    if resultado["calificacion"] >= 90:
        excelentes += 1

promedio = suma_calificaciones / len(resultados)

print("-" * 40)
print(f"Estudiantes procesados: {len(resultados)}")
print(f"Aprobados: {aprobados}")
print(f"Excelentes: {excelentes}")
print(f"Promedio general: {promedio:.2f}")

REPORTE DE CALIFICACIONES
----------------------------------------
Ana        |  95 | Excelente
Luis       |  72 | Aprobado
Marta      |  58 | Reprobado
Carlos     |  84 | Muy bueno
Sofia      |  40 | Reprobado
----------------------------------------
Estudiantes procesados: 5
Aprobados: 3
Excelentes: 1
Promedio general: 69.80

In [9]:
# Modifica el programa anterior para cumplir estos requisitos:
#
# 1. Agrega al menos tres estudiantes.
# 2. Clasifica como:
#    - Excelente: calificación >= 90
#    - Muy bueno: calificación >= 80
#    - Aprobado: calificación >= 70
#    - Regular: calificación >= 60
#    - Reprobado: calificación < 60
# 3. Utiliza un while para procesar la lista.
# 4. Utiliza un for para encontrar la calificación más alta.
# 5. Utiliza if/elif/else para clasificar cada estudiante.
# 6. Calcula el porcentaje de estudiantes aprobados.
#
# Escribe tu solución aquí:

### Ver solución

<details>
<summary><strong>Haz clic aquí para mostrar la solución</strong></summary>

```python
estudiantes = [
    {"nombre": "Ana", "calificacion": 95},
    {"nombre": "Luis", "calificacion": 72},
    {"nombre": "Marta", "calificacion": 58},
    {"nombre": "Carlos", "calificacion": 84},
    {"nombre": "Sofia", "calificacion": 40},
    {"nombre": "Pedro", "calificacion": 67},
    {"nombre": "Lucia", "calificacion": 91},
    {"nombre": "Diego", "calificacion": 76}
]

resultados = []
indice = 0

# WHILE: procesar a todos los estudiantes
while indice < len(estudiantes):
    estudiante = estudiantes[indice]
    calificacion = estudiante["calificacion"]

    # IF / ELIF / ELSE: clasificar la calificación
    if calificacion >= 90:
        nivel = "Excelente"
    elif calificacion >= 80:
        nivel = "Muy bueno"
    elif calificacion >= 70:
        nivel = "Aprobado"
    elif calificacion >= 60:
        nivel = "Regular"
    else:
        nivel = "Reprobado"

    resultados.append({
        "nombre": estudiante["nombre"],
        "calificacion": calificacion,
        "nivel": nivel
    })

    indice += 1

# FOR: mostrar el reporte
print("REPORTE DE CALIFICACIONES")
print("-" * 45)

for resultado in resultados:
    print(
        f"{resultado['nombre']:<10} | "
        f"{resultado['calificacion']:>3} | "
        f"{resultado['nivel']}"
    )

# FOR: encontrar la calificación más alta
calificacion_maxima = resultados[0]["calificacion"]

for resultado in resultados:
    if resultado["calificacion"] > calificacion_maxima:
        calificacion_maxima = resultado["calificacion"]

# FOR + IF: contar aprobados
aprobados = 0

for resultado in resultados:
    if resultado["calificacion"] >= 70:
        aprobados += 1

total_estudiantes = len(resultados)

if total_estudiantes > 0:
    porcentaje_aprobados = aprobados / total_estudiantes * 100
else:
    porcentaje_aprobados = 0

print("-" * 45)
print(f"Total de estudiantes: {total_estudiantes}")
print(f"Calificación más alta: {calificacion_maxima}")
print(f"Estudiantes aprobados: {aprobados}")
print(f"Porcentaje de aprobados: {porcentaje_aprobados:.2f}%")
```

</details>

## Diccionarios en Python (`dict`)

Un **diccionario** es una estructura de datos que permite almacenar y organizar información en pares de **clave y valor** (*key-value pairs*). Cada clave sirve como identificador para acceder al valor asociado.

Los diccionarios son útiles para representar información estructurada, como los datos de una persona, las características de un producto o la configuración de una aplicación.

### Características principales

- **Claves únicas:** cada clave aparece una sola vez; si se asigna nuevamente, su valor se actualiza.
- **Acceso mediante claves:** los valores se consultan utilizando sus claves, en lugar de índices numéricos.
- **Mutabilidad:** es posible agregar, modificar y eliminar elementos después de crear el diccionario.
- **Tipos de datos flexibles:** las claves suelen ser cadenas de texto, aunque también pueden ser otros tipos inmutables. Los valores pueden ser de distintos tipos, como números, cadenas, listas, booleanos u otros diccionarios.
- **Orden de inserción:** Python conserva el orden en que se agregan los elementos.

### Sintaxis

Los diccionarios se crean utilizando llaves `{}`, separando cada clave de su valor mediante dos puntos (`:`) y los pares mediante comas.

```python
diccionario = {
    "clave1": "valor1",
    "clave2": "valor2",
    "clave3": "valor3"
}
```

### Operaciones básicas

- **Consultar:** obtener un valor mediante su clave.
- **Agregar:** incorporar un nuevo par de clave y valor.
- **Modificar:** cambiar el valor asociado a una clave existente.
- **Eliminar:** quitar un elemento del diccionario.
- **Recorrer:** iterar sobre sus claves, valores o pares mediante ciclos.

En Python, el tipo de dato de un diccionario es `dict`.

Los diccionarios permiten representar información de manera clara y acceder a ella mediante identificadores significativos, lo que facilita la lectura y el mantenimiento del código.

In [11]:
#Ejemplo basico
persona = {
    "nombre": "Ana",
    "edad": 25,
    "ciudad": "Ciudad de México"
}

# Acceder a un valor
print(persona["nombre"])

# Modificar un valor
persona["edad"] = 26

# Agregar una nueva clave
persona["profesion"] = "Ingeniera"

print(persona)

Ana
{'nombre': 'Ana', 'edad': 26, 'ciudad': 'Ciudad de México', 'profesion': 'Ingeniera'}

In [12]:
#Ejemplo intermedio
inventario = {
    "Laptop": 15000,
    "Mouse": 350,
    "Teclado": 800,
    "Monitor": 4200
}

total = 0

for producto, precio in inventario.items():
    print(f"{producto}: ${precio}")
    total += precio

print(f"Valor total: ${total}")

Laptop: $15000
Mouse: $350
Teclado: $800
Monitor: $4200
Valor total: $20350

In [15]:
#Ejemplo avanzado
ventas = [
    {"producto": "Laptop", "cantidad": 3, "precio": 15000},
    {"producto": "Mouse", "cantidad": 10, "precio": 350},
    {"producto": "Monitor", "cantidad": 4, "precio": 4200},
    {"producto": "Teclado", "cantidad": 6, "precio": 800}
]

total_ventas = 0
producto_mayor_venta = ""
mayor_venta = 0

for venta in ventas:
    subtotal = venta["cantidad"] * venta["precio"]
    total_ventas += subtotal

    print(f"{venta['producto']}: ${subtotal:,.2f}")

    if subtotal > mayor_venta:
        mayor_venta = subtotal
        producto_mayor_venta = venta["producto"]

print("-" * 35)
print(f"Total de ventas: ${total_ventas:,.2f}")
print(f"Mayor venta: {producto_mayor_venta}")
print(f"Importe mayor: ${mayor_venta:,.2f}")

Laptop: $45,000.00
Mouse: $3,500.00
Monitor: $16,800.00
Teclado: $4,800.00
-----------------------------------
Total de ventas: $70,100.00
Mayor venta: Laptop
Importe mayor: $45,000.00

## Funciones en Python (`def`)

Una **función** es un bloque de código reutilizable que realiza una tarea específica. Permite organizar el código, evitar repeticiones y facilitar su mantenimiento.

### Sintaxis

```python
def nombre_funcion(parametros):
    # Instrucciones
    return resultado
```

- **`def`:** palabra clave para definir una función.
- **Nombre:** identificador de la función.
- **Parámetros:** datos que recibe la función (opcionales).
- **`return`:** devuelve un resultado (opcional).

### Ejemplo

```python
def sumar(a, b):
    return a + b

resultado = sumar(5, 3)
print(resultado)
```

**Salida:**
```text
8
```

Para ejecutar una función, debemos **llamarla por su nombre** y proporcionar los argumentos necesarios.

Las funciones pueden recibir parámetros, devolver resultados o simplemente ejecutar instrucciones.

In [16]:

def mostrar_mensaje():
    print("Bienvenido al curso de Python")
    print("Aprenderemos a utilizar funciones.")

mostrar_mensaje()

Bienvenido al curso de Python
Aprenderemos a utilizar funciones.

In [17]:

def calcular_promedio(nota1, nota2, nota3):
    promedio = (nota1 + nota2 + nota3) / 3
    return promedio

resultado = calcular_promedio(90, 85, 95)

print(f"Promedio: {resultado:.2f}")

Promedio: 90.00

In [18]:

def analizar_ventas(ventas):
    total = 0
    producto_mayor = ""
    mayor_importe = 0

    for venta in ventas:
        importe = venta["cantidad"] * venta["precio"]
        total += importe

        if importe > mayor_importe:
            mayor_importe = importe
            producto_mayor = venta["producto"]

    return {
        "total_ventas": total,
        "producto_mayor": producto_mayor,
        "mayor_importe": mayor_importe
    }


ventas = [
    {"producto": "Laptop", "cantidad": 3, "precio": 15000},
    {"producto": "Mouse", "cantidad": 10, "precio": 350},
    {"producto": "Monitor", "cantidad": 4, "precio": 4200}
]

resumen = analizar_ventas(ventas)

print(f"Total de ventas: ${resumen['total_ventas']:,.2f}")
print(f"Producto destacado: {resumen['producto_mayor']}")
print(f"Mayor importe: ${resumen['mayor_importe']:,.2f}")

Total de ventas: $65,300.00
Producto destacado: Laptop
Mayor importe: $45,000.00

## Pandas en Python

**Pandas** es una biblioteca de Python que permite manipular, organizar y analizar datos de forma eficiente. Es especialmente útil para trabajar con tablas de datos, archivos CSV y Excel.

### Estructuras principales

- **`Series`:** estructura unidimensional que almacena datos, similar a una columna.
- **`DataFrame`:** estructura bidimensional organizada en filas y columnas, similar a una tabla.

### Importar Pandas

```python
import pandas as pd
```

La abreviatura `pd` es la convención utilizada para acceder a las funciones de Pandas.

### Operaciones comunes

- Crear tablas a partir de datos.
- Leer y guardar archivos CSV y Excel.
- Seleccionar filas y columnas.
- Filtrar y ordenar información.
- Calcular estadísticas y resumir datos.

Pandas es una herramienta fundamental para el análisis de datos, la exploración de información y la preparación de datos para proyectos de ciencia de datos y aprendizaje automático.

In [19]:

import pandas as pd

datos = {
    "Producto": ["Laptop", "Mouse", "Teclado", "Monitor", "Laptop"],
    "Precio": [15000, 350, 800, 4200, 15000],
    "Cantidad": [2, 10, 5, 3, 1],
    "Categoria": ["Computo", "Accesorios", "Accesorios", "Computo", "Computo"]
}

df = pd.DataFrame(datos)

df

  Producto  Precio  Cantidad   Categoria
0   Laptop   15000         2     Computo
1    Mouse     350        10  Accesorios
2  Teclado     800         5  Accesorios
3  Monitor    4200         3     Computo
4   Laptop   15000         1     Computo

In [23]:
# Mostrar las primeras filas
df.head(2)

  Producto  Precio  Cantidad   Categoria
0   Laptop   15000         2     Computo
1    Mouse     350        10  Accesorios

In [24]:
# Consultar las dimensiones (filas, columnas)
df.shape

(5, 4)

In [25]:
# Consultar los tipos de datos
df.dtypes

Producto     object
Precio        int64
Cantidad      int64
Categoria    object
dtype: object

In [26]:
# Seleccionar una columna
df["Producto"]

0     Laptop
1      Mouse
2    Teclado
3    Monitor
4     Laptop
Name: Producto, dtype: object

In [27]:
# Seleccionar varias columnas
df[["Producto", "Precio"]]

  Producto  Precio
0   Laptop   15000
1    Mouse     350
2  Teclado     800
3  Monitor    4200
4   Laptop   15000

In [28]:
# Productos con precio mayor a $1,000
df[df["Precio"] > 1000]

  Producto  Precio  Cantidad Categoria
0   Laptop   15000         2   Computo
3  Monitor    4200         3   Computo
4   Laptop   15000         1   Computo

In [29]:
# Ordenar por precio de mayor a menor
df.sort_values("Precio", ascending=False)

  Producto  Precio  Cantidad   Categoria
0   Laptop   15000         2     Computo
4   Laptop   15000         1     Computo
3  Monitor    4200         3     Computo
2  Teclado     800         5  Accesorios
1    Mouse     350        10  Accesorios

In [30]:
# Calcular el importe por producto
df["Importe"] = df["Precio"] * df["Cantidad"]

df

  Producto  Precio  Cantidad   Categoria  Importe
0   Laptop   15000         2     Computo    30000
1    Mouse     350        10  Accesorios     3500
2  Teclado     800         5  Accesorios     4000
3  Monitor    4200         3     Computo    12600
4   Laptop   15000         1     Computo    15000

In [31]:
# Precio promedio
print(df["Precio"].mean())

# Importe total de las ventas
print(df["Importe"].sum())

# Cantidad total vendida
print(df["Cantidad"].sum())

7070.0
65100
21

In [32]:
# Importe total por categoría
df.groupby("Categoria")["Importe"].sum()

Categoria
Accesorios     7500
Computo       57600
Name: Importe, dtype: int64

## Operaciones básicas para analizar datos con Pandas

Pandas permite explorar, filtrar, transformar y resumir información almacenada en un `DataFrame`.

### 1. Visualizar las primeras filas: `head()`

Muestra las primeras cinco filas por defecto. Puedes indicar cuántas filas deseas consultar.

```python
df.head()      # Primeras 5 filas
df.head(10)    # Primeras 10 filas
```

### 2. Consultar la estructura: `columns`, `shape` e `info()`

Permiten conocer los nombres de las columnas, las dimensiones de la tabla y los tipos de datos.

```python
df.columns     # Nombres de las columnas
df.shape       # Número de filas y columnas
df.info()      # Tipos de datos y valores no nulos
```

### 3. Filtrar y ordenar información

El filtrado selecciona las filas que cumplen una condición. La ordenación organiza los registros según una columna.

```python
# Filtrar filas
df[df["Precio"] > 1000]

# Ordenar de mayor a menor
df.sort_values("Precio", ascending=False)

# Ordenar de menor a mayor
df.sort_values("Precio", ascending=True)
```

### 4. Crear una nueva columna

Permite agregar información calculada a partir de columnas existentes.

```python
# Calcular el importe de cada registro
df["Importe"] = df["Precio"] * df["Cantidad"]
```

### 5. Calcular estadísticas: `mean()` y `sum()`

Permiten obtener estadísticas básicas de una columna numérica.

```python
df["Precio"].mean()       # Precio promedio
df["Cantidad"].sum()      # Cantidad total
df["Importe"].sum()       # Importe total
```

### 6. Agrupar información: `groupby()`

Agrupa los registros según una columna para calcular resúmenes por categoría.

```python
# Sumar el importe de las ventas por producto
df.groupby("Producto")["Importe"].sum()

# Calcular el precio promedio por categoría
df.groupby("Categoria")["Precio"].mean()
```

**En resumen:** estas operaciones permiten inspeccionar los datos, seleccionar información relevante, crear nuevos cálculos y obtener estadísticas para facilitar el análisis.

# Reto basico Presentacion
-  1. Crea un DataFrame con producto, categoría y unidades.
-  2. Calcula el total de unidades.
-  3. Filtra productos con al menos 10 unidades.
-  4. Crea una función que clasifique el inventario: “Alto” si unidades ≥ 10; “Bajo” en caso contrario.
-  Tiempo sugerido: 6 minutos en parejas o individual.

<details>
<summary><strong>Haz clic aquí para mostrar la solución</strong></summary>

```python
import pandas as pd

df_inv = pd.DataFrame({
    "producto": ["Cuaderno", "Lápiz", "Mochila", "Regla"],
    "categoria": ["Papelería", "Papelería", "Accesorios", "Papelería"],
    "unidades": [15, 8, 12, 5]
})

# Calcular el total de unidades
print("Total de unidades:", df_inv["unidades"].sum())

# Filtrar productos con al menos 10 unidades
print(df_inv[df_inv["unidades"] >= 10])

# Función para clasificar el inventario
def clasificar_inventario(unidades):
    if unidades >= 10:
        return "Alto"
    return "Bajo"

# Crear una columna con la clasificación
df_inv["inventario"] = df_inv["unidades"].apply(clasificar_inventario)

# Mostrar el DataFrame final
df_inv
```

</details>

### Conceptos utilizados

- **`pd.DataFrame()`**: crea una tabla a partir de los datos.
- **`sum()`**: calcula la suma de las unidades.
- **Filtrado**: `df_inv[df_inv["unidades"] >= 10]` muestra los productos con 10 unidades o más.
- **Función personalizada**: `clasificar_inventario()` devuelve `"Alto"` o `"Bajo"` según la cantidad.
- **`apply()`**: aplica la función a cada valor de la columna `unidades` y guarda el resultado en la nueva columna `inventario`.

In [ ]:


### Código

# Pandas Nivel Intermedio
## 1. GroupBy y Pivot Tables

Permiten **agrupar y resumir datos** para analizar información por categorías.

- `groupby()` agrupa registros según una o varias columnas y permite calcular sumas, promedios y otras estadísticas.
- `pivot_table()` crea una tabla resumen que organiza los datos por filas y columnas, facilitando la comparación entre categorías.

```python
# Agrupar y calcular ventas por producto
df.groupby("Producto")["Importe"].sum()

# Crear una tabla dinámica
pd.pivot_table(
    df,
    values="Importe",
    index="Producto",
    columns="Categoria",
    aggfunc="sum",
    fill_value=0
)
```

## 2. Map y Apply

Permiten **transformar datos mediante funciones**.

- `map()` aplica una correspondencia o función a cada elemento de una `Series`, por ejemplo, convertir códigos en nombres.
- `apply()` permite aplicar una función a una columna o a cada fila o columna de un `DataFrame`.

```python
# Reemplazar códigos por nombres
df["Categoria"] = df["Categoria"].map({
    "A": "Accesorios",
    "C": "Computadoras"
})

# Aplicar una operación a una columna
df["Precio_con_IVA"] = df["Precio"].apply(
    lambda precio: precio * 1.16
)
```

## 3. Merge

Permite **combinar dos DataFrames utilizando una columna en común**, de forma similar a las uniones (`JOIN`) de SQL.

```python
resultado = pd.merge(
    ventas,
    productos,
    on="Producto",
    how="inner"
)
```

El parámetro `how` define el tipo de unión: `inner`, `left`, `right` u `outer`.

## 4. Append y concatenación

Permiten **unir datos de varias tablas**. El método `DataFrame.append()` ya no está disponible en versiones modernas de Pandas; se utiliza `pd.concat()`.

```python
# Unir dos DataFrames por filas
resultado = pd.concat(
    [df_enero, df_febrero],
    ignore_index=True
)
```

`ignore_index=True` genera un nuevo índice consecutivo para las filas combinadas.

## 5. Exportar datos

Pandas permite guardar los resultados en archivos para compartirlos o utilizarlos en otras aplicaciones.

```python
# Exportar a CSV
df.to_csv("resultados.csv", index=False)

# Exportar a Excel
df.to_excel("resultados.xlsx", index=False)
```

El parámetro `index=False` evita exportar el índice como una columna adicional.

Estas operaciones permiten resumir información, transformar valores, combinar fuentes de datos y guardar los resultados de un análisis.

# Ejemplo Basico

In [63]:
### Datos de ejemplo

datos_basico = {
    "producto": ["Teclado", "Mouse", "Monitor", "Webcam", "Audífonos"],
    "categoria": ["Accesorios", "Accesorios", "Pantallas", "Accesorios", "Audio"],
    "precio": [700, 250, 3200, 800, 900],
    "unidades_vendidas": [12, 25, 7, 10, 18]
}

df_basico = pd.DataFrame(datos_basico)

display(df_basico.head())
df_basico["ingresos"] = df_basico["precio"] * df_basico["unidades_vendidas"]
display(df_basico[df_basico["ingresos"] >= 1000].sort_values("ingresos", ascending=False))

    producto   categoria  precio  unidades_vendidas
0    Teclado  Accesorios     700                 12
1      Mouse  Accesorios     250                 25
2    Monitor   Pantallas    3200                  7
3     Webcam  Accesorios     800                 10
4  Audífonos       Audio     900                 18

    producto   categoria  precio  unidades_vendidas  ingresos
2    Monitor   Pantallas    3200                  7     22400
4  Audífonos       Audio     900                 18     16200
0    Teclado  Accesorios     700                 12      8400
3     Webcam  Accesorios     800                 10      8000
1      Mouse  Accesorios     250                 25      6250

In [64]:
resumen = (
    df_basico.groupby("categoria")
      .agg(
          ingresos_totales=("ingresos", "sum"),
          unidades_totales=("unidades_vendidas", "sum")
      )
      .reset_index()
)
display(resumen.sort_values("ingresos_totales", ascending=False))
top = resumen.loc[resumen["ingresos_totales"].idxmax(), "categoria"]
print("Categoría con más ingresos:", top)

    categoria  ingresos_totales  unidades_totales
0  Accesorios             22650                47
2   Pantallas             22400                 7
1       Audio             16200                18

Categoría con más ingresos: Accesorios

In [65]:
# Crear una tabla dinámica
tabla_dinamica = pd.pivot_table(
    df_basico,
    values="ingresos",
    index="categoria",
    columns="producto",
    aggfunc="sum",
    fill_value=0
)

display(tabla_dinamica)

producto    Audífonos  Monitor  Mouse  Teclado  Webcam
categoria
Accesorios          0        0   6250     8400    8000
Audio           16200        0      0        0       0
Pantallas           0    22400      0        0       0

In [66]:
# Diccionario para traducir las categorías
mapa_categorias = {
    "Accesorios": "Complementos",
    "Pantallas": "Monitores",
    "Audio": "Sonido"
}

# Crear una nueva columna con las categorías traducidas
df_basico["categoria_descripcion"] = (
    df_basico["categoria"].map(mapa_categorias)
)

display(df_basico)

,producto,categoria,precio,unidades_vendidas,ingresos,categoria_descripcion
0,Teclado,Accesorios,700,12,8400,Complementos
1,Mouse,Accesorios,250,25,6250,Complementos
2,Monitor,Pantallas,3200,7,22400,Monitores
3,Webcam,Accesorios,800,10,8000,Complementos
4,Audífonos,Audio,900,18,16200,Sonido

In [68]:
df_basico["precio_con_iva"] = df_basico["precio"].apply(
    lambda precio: precio * 1.16
)

display(df_basico[["producto", "precio", "precio_con_iva"]])

    producto  precio  precio_con_iva
0    Teclado     700           812.0
1      Mouse     250           290.0
2    Monitor    3200          3712.0
3     Webcam     800           928.0
4  Audífonos     900          1044.0

In [69]:
datos_proveedores = {
    "producto": ["Teclado", "Mouse", "Monitor", "Webcam", "Audífonos"],
    "proveedor": ["Logitech", "HP", "Samsung", "Logitech", "Sony"]
}

df_proveedores = pd.DataFrame(datos_proveedores)

display(df_proveedores)

    producto proveedor
0    Teclado  Logitech
1      Mouse        HP
2    Monitor   Samsung
3     Webcam  Logitech
4  Audífonos      Sony

In [71]:
datos_nuevos = {
    "producto": ["Micrófono", "Bocinas"],
    "categoria": ["Audio", "Audio"],
    "precio": [1200, 1500],
    "unidades_vendidas": [8, 6]
}

df_nuevos = pd.DataFrame(datos_nuevos)

df_concatenado = pd.concat(
    [df_basico, df_nuevos],
    ignore_index=True
)

display(df_concatenado)

,producto,categoria,precio,unidades_vendidas,ingresos,categoria_descripcion,precio_con_iva
0,Teclado,Accesorios,700,12,8400.0,Complementos,812.0
1,Mouse,Accesorios,250,25,6250.0,Complementos,290.0
2,Monitor,Pantallas,3200,7,22400.0,Monitores,3712.0
3,Webcam,Accesorios,800,10,8000.0,Complementos,928.0
4,Audífonos,Audio,900,18,16200.0,Sonido,1044.0
5,Micrófono,Audio,1200,8,NaN,NaN,NaN
6,Bocinas,Audio,1500,6,NaN,NaN,NaN

In [ ]:
# Exportar a CSV
df_basico.to_csv("ventas.csv", index=False)

# Exportar a Excel
df_basico.to_excel("ventas.xlsx", index=False)

## Cargar un archivo CSV con Pandas

Para cargar un archivo CSV en Python, utilizamos `pandas.read_csv()`, que permite leer los datos y almacenarlos en un DataFrame.

```python
import pandas as pd

df = pd.read_csv("datos.csv")

display(df.head())
```

- `import pandas as pd`: importa la librería Pandas.
- `pd.read_csv("datos.csv")`: carga el archivo CSV en un DataFrame.
- `df.head()`: muestra las primeras cinco filas para revisar los datos.

**Nota:** el archivo debe estar en la carpeta de trabajo del notebook o debes indicar su ruta completa.

# Tarea Carga tu propio CSV

# Ejemplo Avanzado

Dataset: Online Learning Platform

Cada fila representa la actividad de un usuario en una fecha determinada.

**Significado de las columnas:**

| Columna | Descripción |
|---|---|
| `user_id` | Identificador único del usuario |
| `date` | Fecha de actividad |
| `lessons_completed` | Lecciones completadas |
| `minutes_spent` | Minutos dedicados a la plataforma |
| `quizzes_attempted` | Cuestionarios intentados |
| `subscription_type` | Tipo de suscripción: `Gratuito` o `Premium` |

In [33]:
import pandas as pd

datos_comp = {
    "user_id": [101, 102, 103, 104, 105, 101, 102, 103, 106, 107],
    "date": [
        "2024-01-01", "2024-01-01", "2024-01-02",
        "2024-01-02", "2024-01-03", "2024-01-04",
        "2024-01-04", "2024-01-05", "2024-01-05",
        "2024-01-06"
    ],
    "lessons_completed": [3, 1, 5, 2, 0, 4, 2, 6, 1, 3],
    "minutes_spent": [45, 15, 80, 30, 5, 60, 25, 95, 20, 40],
    "quizzes_attempted": [2, 1, 4, 2, 0, 3, 1, 5, 1, 2],
    "subscription_type": [
        "Premium", "Gratuito", "Premium", "Gratuito",
        "Gratuito", "Premium", "Gratuito", "Premium",
        "Gratuito", "Premium"
    ]
}

df = pd.DataFrame(datos_comp)

df["date"] = pd.to_datetime(df["date"])

df

,user_id,date,lessons_completed,minutes_spent,quizzes_attempted,subscription_type
0,101,2024-01-01,3,45,2,Premium
1,102,2024-01-01,1,15,1,Gratuito
2,103,2024-01-02,5,80,4,Premium
3,104,2024-01-02,2,30,2,Gratuito
4,105,2024-01-03,0,5,0,Gratuito
5,101,2024-01-04,4,60,3,Premium
6,102,2024-01-04,2,25,1,Gratuito
7,103,2024-01-05,6,95,5,Premium
8,106,2024-01-05,1,20,1,Gratuito
9,107,2024-01-06,3,40,2,Premium

In [34]:
resumen = df.groupby("subscription_type")[
    ["lessons_completed", "minutes_spent", "quizzes_attempted"]
].mean()

print(resumen)

                   lessons_completed  minutes_spent  quizzes_attempted
subscription_type
Gratuito                         1.2           19.0                1.0
Premium                          4.2           64.0                3.2

In [35]:
resumen = resumen.round(2)
resumen

                   lessons_completed  minutes_spent  quizzes_attempted
subscription_type
Gratuito                         1.2           19.0                1.0
Premium                          4.2           64.0                3.2

In [36]:
df.groupby("subscription_type")["user_id"].count()

subscription_type
Gratuito    5
Premium     5
Name: user_id, dtype: int64

In [37]:
tabla = pd.pivot_table(
    df,
    values=["lessons_completed", "minutes_spent"],
    index="subscription_type",
    aggfunc="mean"
)

tabla.round(2)

                   lessons_completed  minutes_spent
subscription_type
Gratuito                         1.2           19.0
Premium                          4.2           64.0

In [38]:
tabla_fecha = pd.pivot_table(
    df,
    values="minutes_spent",
    index="date",
    columns="subscription_type",
    aggfunc="mean",
    fill_value=0
)

tabla_fecha

subscription_type  Gratuito  Premium
date
2024-01-01             15.0     45.0
2024-01-02             30.0     80.0
2024-01-03              5.0      0.0
2024-01-04             25.0     60.0
2024-01-05             20.0     95.0
2024-01-06              0.0     40.0

In [39]:
etiquetas = {
    "Gratuito": "Plan sin costo",
    "Premium": "Plan de pago"
}

df["subscription_description"] = df["subscription_type"].map(etiquetas)

df[["user_id", "subscription_type", "subscription_description"]]

   user_id subscription_type subscription_description
0      101           Premium             Plan de pago
1      102          Gratuito           Plan sin costo
2      103           Premium             Plan de pago
3      104          Gratuito           Plan sin costo
4      105          Gratuito           Plan sin costo
5      101           Premium             Plan de pago
6      102          Gratuito           Plan sin costo
7      103           Premium             Plan de pago
8      106          Gratuito           Plan sin costo
9      107           Premium             Plan de pago

In [40]:
def clasificar_actividad(minutos):
    if minutos < 20:
        return "Baja"
    elif minutos < 60:
        return "Media"
    else:
        return "Alta"

df["activity_level"] = df["minutes_spent"].apply(clasificar_actividad)

df[["user_id", "minutes_spent", "activity_level"]]

   user_id  minutes_spent activity_level
0      101             45          Media
1      102             15           Baja
2      103             80           Alta
3      104             30          Media
4      105              5           Baja
5      101             60           Alta
6      102             25          Media
7      103             95           Alta
8      106             20          Media
9      107             40          Media

In [41]:
### Combinar dos DataFrames

usuarios = pd.DataFrame({
    "user_id": [101, 102, 103, 104, 105, 106, 107],
    "country": [
        "Mexico", "Colombia", "Mexico", "Chile",
        "Peru", "Mexico", "Colombia"
    ],
    "signup_date": [
        "2023-12-01", "2023-12-05", "2023-12-10",
        "2023-12-15", "2023-12-20", "2023-12-25",
        "2023-12-28"
    ]
})

resultado = pd.merge(
    df,
    usuarios,
    on="user_id",
    how="left"
)

resultado[[
    "user_id", "subscription_type", "country", "minutes_spent"
]]

   user_id subscription_type   country  minutes_spent
0      101           Premium    Mexico             45
1      102          Gratuito  Colombia             15
2      103           Premium    Mexico             80
3      104          Gratuito     Chile             30
4      105          Gratuito      Peru              5
5      101           Premium    Mexico             60
6      102          Gratuito  Colombia             25
7      103           Premium    Mexico             95
8      106          Gratuito    Mexico             20
9      107           Premium  Colombia             40

In [42]:
### Agregar nuevos registros

nueva_actividad = pd.DataFrame({
    "user_id": [101, 108],
    "date": pd.to_datetime(["2024-01-07", "2024-01-07"]),
    "lessons_completed": [5, 2],
    "minutes_spent": [70, 25],
    "quizzes_attempted": [4, 1],
    "subscription_type": ["Premium", "Gratuito"]
})

df_actualizado = pd.concat(
    [df, nueva_actividad],
    ignore_index=True
)

df_actualizado.tail()

,user_id,date,lessons_completed,minutes_spent,quizzes_attempted,subscription_type,subscription_description,activity_level
7,103,2024-01-05,6,95,5,Premium,Plan de pago,Alta
8,106,2024-01-05,1,20,1,Gratuito,Plan sin costo,Media
9,107,2024-01-06,3,40,2,Premium,Plan de pago,Media
10,101,2024-01-07,5,70,4,Premium,NaN,NaN
11,108,2024-01-07,2,25,1,Gratuito,NaN,NaN

In [43]:
### Exportar los datos analizados
# Guardar toda la actividad
df.to_csv("actividad_usuarios.csv", index=False)

# Guardar el resumen por suscripción
resumen = df.groupby("subscription_type")[
    ["lessons_completed", "minutes_spent", "quizzes_attempted"]
].mean()

resumen

                   lessons_completed  minutes_spent  quizzes_attempted
subscription_type
Gratuito                         1.2           19.0                1.0
Premium                          4.2           64.0                3.2

In [ ]:
resumen.to_csv("resumen_suscripciones.csv")